variable "AWS_REGION" { default = "us-east-2" }
variable "APPRUNNER_PORT" { default = "8080" }
variable "APPRUNNER_RUNTIME" { default = "CORRETTO_11" }
variable "JMX_File" { default = "my_test" }                                    // jmeter file name without extension
variable "S3BUCKET_NAME" { default = "loveisair" }                             // S3 bucket to store test results
variable "SHELL_FILE" { default = "run_test_new.sh" }                          // shell file which does the entire job in AppRunner container
variable "REPO" { default = "https://github.com/myanees284/apprunner-jmeter" } // this is my github repo.
variable "S3_ROLE" { default = "S3-role-ARN-NAME" }
variable "SERVICE_NAME" { default = "super-service" }
variable "GITHUB_CONNECTIONS" { default = "APPRUNNER-GITHUB-CONNECTIONS-ARN-NAME" }